---
- name: Ensure icescrum.jar is present.
  stat:
    path: "{{ icescrum_install_dir }}/icescrum.jar"
  register: icescrum_jar

- name: Ensure icescrum directory is present.
  file:
    path: "{{ icescrum_install_dir }}"
    state: directory

- name: Download icescrum.jar.
  get_url:
    url: "{{ icescrum_jar_url }}"
    dest: "{{ icescrum_install_dir }}/icescrum.jar"
  when: icescrum_jar.stat.exists == false

- name: Ensure icescrum ownership.
  file:
    path: "{{ icescrum_install_dir }}"
    owner: "{{ icescrum_user }}"
    group: "{{ icescrum_group }}"
    recurse: yes

- name: Ensure temporary directories are present.
  file:
    path: "{{ icescrum_work_dir }}/{{Â item }}"
    owner: "{{ icescrum_user }}"
    group: "{{ icescrum_group }}"
    mode: 0755
    state: directory
  with_items:
  - icescrum-tomcat
  - standalone-war
